---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: authentication-service
  name: authentication-service
spec:
  ports:
  - port: 8095
    protocol: TCP
    targetPort: 8095
  selector:
    app: authentication-service
  type: ClusterIP
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
  labels:
    app: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
      - name: user-service
        image: param036/wednight_authentication-service:wednight_authentication-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8095
        env:
        - name: servername_eureka
          value: "eureka-server"
        - name: servername_db
          value: "mysql"
...
