---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: email-service
  name: email-service
spec:
  ports:
  - port: 8075
    protocol: TCP
    targetPort: 8075
  selector:
    app: email-service
  type: ClusterIP
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
  labels:
    app: email-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
      - name: email-service
        image: param036/wednight_email-service:wednight_email-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8075
        env:
        - name: servername_eureka
          value: "eureka-server"
...
