---
apiVersion: v1
kind: Service
metadata:
  name: mongo-container
  labels:
   app: mongo
spec:
  ports:
  - port: 27017
  clusterIP: None
  selector:
    app: mongo
...
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: "mongodb"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
     # terminationGracePeriodSeconds: 10
      containers:
      - name: mongo-container
        image: supree196/mongo:latest
        
        ports:
        - containerPort: 27017
        
...
