---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
   app: project
spec:
  ports:
  - port: 3306
  clusterIP: None
  selector:
    app: mysql
...
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: supree196/mysql:latest
        imagePullPolicy: IfNotPresent
        
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_USERNAME
            value: 'root'
          - name: MYSQL_ROOT_PASSWORD
            value: 'Password'
...
