---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tag-service
  name: tag-service
spec:
  ports:
  - port: 8070
    protocol: TCP
    targetPort: 8070
  selector:
    app: tag-service
  type: ClusterIP
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tag-service
  labels:
    app: tag-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tag-service
  template:
    metadata:
      labels:
        app: tag-service
    spec:
      containers:
      - name: tag-service
        image: param036/wednight_tag-service:wednight_tag-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8070
        env:
        - name: servername_eureka
          value: "eureka-server"
        - name: servername_mongodb
          value: "mongodb"
...
